language: node_js

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/waiter_test

node_js:
  - "12.18.3"

before_script:
  - psql -c 'create database  waiter_test;' -U postgres
  - psql -U postgres -d waiter_test -a -f waiter_test.sql

services:
  - postgresql